#!/usr/bin/env bash
# 由 hypr/hyprbars-whitelist.txt 生成 hypr/hyprbars-show.conf
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
list="$root/hypr/hyprbars-whitelist.txt"
out="$root/hypr/hyprbars-show.conf"

if [[ ! -f "$list" ]]; then
	echo "missing whitelist: $list" >&2
	exit 1
fi

python3 - "$list" "$out" <<'PY'
import re, sys
from pathlib import Path

list_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
classes = []
for raw in list_path.read_text(encoding="utf-8").splitlines():
    line = raw.strip()
    if not line or line.startswith("#"):
        continue
    classes.append(re.escape(line))

lines = [
    "# AUTO-GENERATED by scripts/hyprbars-whitelist.sh — do not edit",
    "# source: hypr/hyprbars-whitelist.txt",
    "",
]
if not classes:
    lines.append("# (whitelist empty — no show rule)")
else:
    pattern = "^(%s)$" % "|".join(classes)
    lines += [
        "# 白名单：覆盖 hyprbars-default-off，显示标题栏",
        "windowrule {",
        "  name = hyprbars-show-whitelist",
        f"  match:class = {pattern}",
        "  hyprbars:no_bar = off",
        "}",
    ]
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out_path} ({len(classes)} class(es))")
PY
